version: 2.1

orbs:
  node-orb: heug/node@dev:0.0.5

jobs:
  build:
    executor:
      name: node-orb/node # put executor in the name
      tag: "6.14.4"
    parallelism: 3
    steps:
      - checkout
      - run: 
          name: Check Node version
          command: |
            if [ "$(node --version)" == "v6.14.4" ]; then
              exit 0
            else
              exit 1
            fi
      - node-orb/install-package-manager:
          npm: true
          npm_version: 6.0.1
      - run:
          name: Check NPM version
          command: |
            if [ "$(npm --version)" == "6.0.1" ]; then
              exit 0
            else
              exit 1
            fi
      - node-orb/with-cache:
          steps:
            - run: 
                command: npm install
      - run: mkdir -p ~/project/junit
      - node-orb/with-splitting:
          glob-path: "test/**/*.spec.js"
          steps:
            - run: env
            - run: 
                command: npm test --glob ${TESTFILES}
                environment:
                  MOCHA_FILE: ~/project/junit/test-results.xml
                when: always
      - store_test_results:
          path: ~/project/junit
      - store_artifacts:
          path: ~/project/junit
      - run: env

workflows:
  build-test-deploy:
    jobs:
      - build